<!DOCTYPE html>
<html lang="pt-br" dir="ltr">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=7">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <?= $seo->render(); ?>


    <!-- Links CSS -->
    <link rel="stylesheet" href="<?= asset('css/app.css') ?>">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css">
    <?= $this->section('styles') ?>
    <!-- Fim: CSS -->

    <!-- JavaScript -->
    <?= $this->section('scripts') ?>
    <!-- Fim dos scripts JS -->

</head>

<body>
    <main>
        <?= $this->section('main') ?>
    </main>
</body>

</html>