<!DOCTYPE html>
<html lang="pt-br" dir="ltr">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=7">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <meta name="description" content="">
    <meta name="keywords" content="">


    <!-- Links CSS -->
    <link rel="stylesheet" href="<?= asset('css/app.css') ?>">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css">
    <?= $this->section('styles') ?>
    <!-- Fim: CSS -->

    <!-- Título da Página -->
    <title><?= $title ?> | <?= SITE_NAME ?></title>

    <!-- JavaScript -->
    <script defer="defer" src="<?= asset('js/app.js') ?>"></script>
    <?= $this->section('scripts') ?>
    <!-- Fim dos scripts JS -->

</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Mini Framework</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main-nav" aria-controls="main-nav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="main-nav">
            <ul class="navbar-nav">
                <li class="nav-item <?= url('App') == url()->getPath() ? 'active' : '' ?>">
                    <a class="nav-link" href="<?= url('/') ?>">Home <?= url('App') == url()->getPath() ? '<span class="sr-only">(current)</span>' : '' ?></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Contact</a>
                </li>
            </ul>
        </div>
    </nav>
    <main>
        <?= $this->section('main') ?>
    </main>
</body>

</html>