<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=7">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Paǵina não encontrada | <?= SITE_NAME ?></title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300&display=swap" rel="stylesheet">
    <style>
        body {
            margin: 0;
            padding: 0;

            height: 100vh;
            width: 100vw;

            display: flex;
            justify-content: center;
            align-items: center;

            text-align: center;
        }

        * {
            font-family: 'Roboto', sans-serif;
        }


        h3 {
            font-weight: 100;
        }

        span {
            padding: 0 10px;
            margin-right: 10px;
            border-right: 1px solid #ccc;
        }

        a {
            font-weight: 300;
            text-decoration: none;
            color: black;
        }

        a:hover {
            text-decoration: underline;
        }
    </style>
</head>

<body>

    <div>
        <h3><span>404</span>Página não encontrada</h3>
        <a href="<?= url('/') ?>">Ir para página inicial</a>
    </div>
</body>

</html>