<?php
$this->layout('layouts/app', [
    'seo' => $seo
]);
?>

<?php $this->start('main') ?>

<section class="welcome-section">
    <h1>{{title}}</h1>
    <ul id="example">
        <li v-for="item in list" :key="item.id">
            {{ item.name }}
        </li>
    </ul>
</section>

<?php $this->stop() ?>

<?php $this->start('scripts') ?>
<script src="<?= asset('js/api.js') ?>" type="text/javascript"></script>
<?php $this->stop() ?>